default:
  # Enketo/Kobo Toolbox Configuration
  enketo:
    base_url: "https://kc.kobotoolbox.org/api/v1"
    username: "service_user"
    password: "service_password"
    pre_survey_form_id: "pre_course_survey_form"
    post_survey_form_id: "post_course_survey_form"
  
  # Posit Cloud Configuration
  posit_cloud:
    base_url: "https://api.rstudiocloud.com/v1"
    api_key: "service_api_key"
    workspace_id: "workspace_123"
  
  # Zoom Configuration
  zoom:
    base_url: "https://api.zoom.us/v2"
    api_key: "service_api_key"
    api_secret: "service_api_secret"
    account_id: "account_id"
  
  # GitHub Configuration
  github:
    base_url: "https://api.github.com"
    token: "service_token"
    organization: "mydscourse"
  
  # PostgreSQL Database Configuration
  database:
    host: "localhost"
    port: 5432
    dbname: "course_analytics"
    user: "service_user"
    password: "service_password"